// Minimal fake UnityEngine API surface, only for syntax/type checking outside Unity.
using System;
using System.Collections.Generic;
namespace UnityEngine {
  public class Object { public string name; public static void Destroy(Object o){} public static void DestroyImmediate(Object o){} public static void Destroy(Object o,float t){} public static implicit operator bool(Object o){return o!=null;} public static T[] FindObjectsOfType<T>() where T:Object{return new T[0];} public static T[] FindObjectsByType<T>(FindObjectsSortMode m) where T:Object{return new T[0];} public static T FindFirstObjectByType<T>() where T:Object{return null;} public static T Instantiate<T>(T o) where T:Object{return o;} }
  public enum FindObjectsSortMode { None, InstanceID }
  public enum PrimitiveType { Sphere, Capsule, Cylinder, Cube, Plane, Quad }
  public enum LightType { Spot, Directional, Point, Area }
  public enum LightShadows { None, Hard, Soft }
  public enum FogMode { Linear = 1, Exponential, ExponentialSquared }
  public enum CursorLockMode { None, Locked, Confined }
  public enum ForceMode { Force, Acceleration, Impulse, VelocityChange }
  public enum RigidbodyInterpolation { None, Interpolate, Extrapolate }
  public enum CollisionDetectionMode { Discrete, Continuous, ContinuousDynamic, ContinuousSpeculative }
  public struct Bounds { public Bounds(Vector3 c,Vector3 s){center=c;size=s;} public Vector3 center,size; }
  public static class ColorUtility { public static string ToHtmlStringRGBA(Color c){return ((int)(c.r*255)).ToString("X2")+((int)(c.g*255)).ToString("X2")+((int)(c.b*255)).ToString("X2")+((int)(c.a*255)).ToString("X2");} }
  public class Shader : Object { public static Shader Find(string n){return new Shader{name=n};} public bool isSupported=true; public static void SetGlobalVector(string n,Vector4 v){} public static void SetGlobalFloat(string n,float f){} public static void SetGlobalColor(string n,Color c){} public static void SetGlobalTexture(string n,Texture t){} }
  public class Material : Object { public Material(Shader s){} public Material(Material m){} public Shader shader; public Color color; public bool HasProperty(string n){return true;} public void SetColor(string n,Color c){} public void SetFloat(string n,float f){} public void SetTexture(string n,Texture t){} public void EnableKeyword(string k){} public Texture mainTexture; }
  public class Mesh : Object { public Vector3[] vertices; public int[] triangles; public Vector3[] normals; public Color[] colors; public Vector2[] uv; public Bounds bounds; public UnityEngine.Rendering.IndexFormat indexFormat; public void RecalculateNormals(){} public void RecalculateBounds(){} public void SetTriangles(int[] t,int sub){} public int subMeshCount; public void Clear(){} }
  public class MeshFilter : Component { public Mesh sharedMesh, mesh; }
  public class MeshCollider : Collider { public Mesh sharedMesh; public bool convex; }
  public class Collider : Component { public bool isTrigger, enabled; public Bounds bounds; }
  public class BoxCollider : Collider { public Vector3 center, size; }
  public class SphereCollider : Collider { public Vector3 center; public float radius; }
  public class CapsuleCollider : Collider { public Vector3 center; public float radius, height; public int direction; }
  public class Rigidbody : Component { public float mass, drag, angularDrag, linearDamping, angularDamping; public bool useGravity, isKinematic, freezeRotation; public Vector3 velocity, linearVelocity, angularVelocity, centerOfMass, position; public Quaternion rotation; public RigidbodyInterpolation interpolation; public CollisionDetectionMode collisionDetectionMode; public void AddForce(Vector3 f,ForceMode m=ForceMode.Force){} public void AddForceAtPosition(Vector3 f,Vector3 p,ForceMode m=ForceMode.Force){} public void AddTorque(Vector3 t,ForceMode m=ForceMode.Force){} public void AddRelativeTorque(Vector3 t,ForceMode m=ForceMode.Force){} public Vector3 GetPointVelocity(Vector3 p){return velocity;} public void MovePosition(Vector3 p){} public void MoveRotation(Quaternion q){} public void WakeUp(){} public float maxAngularVelocity; public Vector3 inertiaTensor; public Quaternion inertiaTensorRotation; }
  public class CharacterController : Collider { public float height, radius, stepOffset, slopeLimit, skinWidth; public Vector3 center; public bool isGrounded; public Vector3 velocity; public CollisionFlags Move(Vector3 m){return CollisionFlags.None;} }
  [Flags] public enum CollisionFlags { None=0, Sides=1, Above=2, Below=4 }
  public struct RaycastHit { public Vector3 point, normal; public float distance; public Collider collider; public Transform transform; public Rigidbody rigidbody; }
  public struct Ray { public Ray(Vector3 o,Vector3 d){origin=o;direction=d;} public Vector3 origin,direction; }
  public static class Physics { public static Vector3 gravity; public static bool Raycast(Vector3 o,Vector3 d,out RaycastHit h,float max=float.PositiveInfinity,int mask=-1){h=new RaycastHit(); return false;} public static bool Raycast(Ray r,out RaycastHit h,float max=float.PositiveInfinity){h=new RaycastHit(); return false;} public static Collider[] OverlapSphere(Vector3 c,float r){return new Collider[0];} public static bool SphereCast(Vector3 o,float r,Vector3 d,out RaycastHit h,float max){h=new RaycastHit(); return false;} public static void IgnoreCollision(Collider a,Collider b,bool i=true){} }
  public class Light : Behaviour { public LightType type; public Color color; public float intensity, range, spotAngle, shadowStrength; public LightShadows shadows; }
  public static class RenderSettings { public static bool fog; public static FogMode fogMode; public static Color fogColor, ambientLight, ambientSkyColor, ambientEquatorColor, ambientGroundColor; public static float fogStartDistance, fogEndDistance, fogDensity; public static UnityEngine.Rendering.AmbientMode ambientMode; public static Material skybox; }
  public class LineRenderer : Renderer { public int positionCount; public float startWidth, endWidth; public Color startColor, endColor; public bool useWorldSpace; public void SetPosition(int i,Vector3 p){} }
  public class TrailRenderer : Renderer { public float time, startWidth, endWidth; }
  public class Component : Object { public GameObject gameObject; public Transform transform; public T GetComponent<T>(){return default(T);} public T[] GetComponentsInChildren<T>(bool inactive=false){return new T[0];} public T GetComponentInChildren<T>(){return default(T);} public T GetComponentInParent<T>(){return default(T);} }
  public class Behaviour : Component { public bool enabled; }
  public class MonoBehaviour : Behaviour {}
  public class ScriptableObject : Object { public static T CreateInstance<T>() where T: ScriptableObject, new() { return new T(); } }
  public class GameObject : Object { public static GameObject CreatePrimitive(PrimitiveType t){var g=new GameObject(t.ToString()); return g;} public GameObject(){} public GameObject(string n){transform=new Transform();} public int layer; public Transform transform; public string tag; public T AddComponent<T>() where T: Component, new(){return new T();} public T GetComponent<T>(){return default(T);} public void SetActive(bool b){activeSelf=b;} public bool activeSelf=true; }
  public class Transform : Component { public Vector3 position, localPosition, localScale, eulerAngles, localEulerAngles; public static bool operator==(Transform a, Transform b){return ReferenceEquals(a,b);} public static bool operator!=(Transform a, Transform b){return !ReferenceEquals(a,b);} public override bool Equals(object o){return ReferenceEquals(this,o);} public override int GetHashCode(){return 0;} public Quaternion rotation, localRotation; public Transform parent; public void SetParent(Transform p, bool w=true){parent=p;} public Vector3 forward{get{return rotation*Vector3.forward;} set{}} public Vector3 right{get{return rotation*Vector3.right;}} public Vector3 up{get{return rotation*Vector3.up;}} public Vector3 TransformPoint(Vector3 p){return position+rotation*p;} public Vector3 InverseTransformPoint(Vector3 p){return Quaternion.Inverse(rotation)*(p-position);} public Vector3 TransformDirection(Vector3 d){return rotation*d;} public Vector3 InverseTransformDirection(Vector3 d){return Quaternion.Inverse(rotation)*d;} public void Rotate(float x,float y,float z){} public void Rotate(Vector3 axis,float a){} public void LookAt(Vector3 p){} public int childCount; public Transform GetChild(int i){return null;} }
  public struct Vector2 { public float x,y; public Vector2(float x,float y){this.x=x;this.y=y;}
    public static Vector2 zero{get{return new Vector2(0,0);}} public static Vector2 one{get{return new Vector2(1,1);}} public static Vector2 right{get{return new Vector2(1,0);}} public static Vector2 left{get{return new Vector2(-1,0);}} public static Vector2 up{get{return new Vector2(0,1);}}
    public float magnitude{get{return (float)Math.Sqrt(x*x+y*y);}} public float sqrMagnitude{get{return x*x+y*y;}} public Vector2 normalized{get{float m=magnitude; return m>1e-5f? this/m : zero;}} public void Normalize(){this=normalized;}
    public static Vector2 operator+(Vector2 a,Vector2 b){return new Vector2(a.x+b.x,a.y+b.y);} public static Vector2 operator-(Vector2 a,Vector2 b){return new Vector2(a.x-b.x,a.y-b.y);} public static Vector2 operator-(Vector2 a){return new Vector2(-a.x,-a.y);}
    public static Vector2 operator*(Vector2 a,float b){return new Vector2(a.x*b,a.y*b);} public static Vector2 operator*(float b,Vector2 a){return a*b;} public static Vector2 operator/(Vector2 a,float b){return new Vector2(a.x/b,a.y/b);}
    public static bool operator==(Vector2 a,Vector2 b){return a.x==b.x&&a.y==b.y;} public static bool operator!=(Vector2 a,Vector2 b){return !(a==b);} public override bool Equals(object o){return o is Vector2 && (Vector2)o==this;} public override int GetHashCode(){return x.GetHashCode()^y.GetHashCode();}
    public static implicit operator Vector3(Vector2 v){return new Vector3(v.x,v.y,0);} public static implicit operator Vector2(Vector3 v){return new Vector2(v.x,v.y);}
    public static float Distance(Vector2 a,Vector2 b){return (a-b).magnitude;} public static Vector2 Lerp(Vector2 a,Vector2 b,float t){t=Mathf.Clamp01(t); return a+(b-a)*t;}
    public static float Dot(Vector2 a,Vector2 b){return a.x*b.x+a.y*b.y;} public static Vector2 ClampMagnitude(Vector2 v,float m){return v.magnitude>m? v.normalized*m : v;} public override string ToString(){return "("+x+", "+y+")";} }
  public struct Vector3 { public static Vector3 Min(Vector3 a,Vector3 b){return new Vector3(System.Math.Min(a.x,b.x),System.Math.Min(a.y,b.y),System.Math.Min(a.z,b.z));} public static Vector3 Max(Vector3 a,Vector3 b){return new Vector3(System.Math.Max(a.x,b.x),System.Math.Max(a.y,b.y),System.Math.Max(a.z,b.z));} public float x,y,z; public Vector3(float x,float y,float z){this.x=x;this.y=y;this.z=z;} public static Vector3 zero{get{return new Vector3(0,0,0);}} public static Vector3 one{get{return new Vector3(1,1,1);}} public static Vector3 up{get{return new Vector3(0,1,0);}} public static Vector3 down{get{return new Vector3(0,-1,0);}} public static Vector3 forward{get{return new Vector3(0,0,1);}} public static Vector3 back{get{return new Vector3(0,0,-1);}} public static Vector3 right{get{return new Vector3(1,0,0);}} public static Vector3 left{get{return new Vector3(-1,0,0);}}
    public static Vector3 operator+(Vector3 a,Vector3 b){return new Vector3(a.x+b.x,a.y+b.y,a.z+b.z);} public static Vector3 operator-(Vector3 a,Vector3 b){return new Vector3(a.x-b.x,a.y-b.y,a.z-b.z);} public static Vector3 operator-(Vector3 a){return new Vector3(-a.x,-a.y,-a.z);} public static Vector3 operator*(Vector3 a,float b){return new Vector3(a.x*b,a.y*b,a.z*b);} public static Vector3 operator*(float b,Vector3 a){return a*b;} public static Vector3 operator/(Vector3 a,float b){return new Vector3(a.x/b,a.y/b,a.z/b);}
    public static bool operator==(Vector3 a,Vector3 b){return a.x==b.x&&a.y==b.y&&a.z==b.z;} public static bool operator!=(Vector3 a,Vector3 b){return !(a==b);} public override bool Equals(object o){return o is Vector3 && (Vector3)o==this;} public override int GetHashCode(){return x.GetHashCode()^y.GetHashCode()^z.GetHashCode();}
    public float magnitude{get{return (float)Math.Sqrt(x*x+y*y+z*z);}} public float sqrMagnitude{get{return x*x+y*y+z*z;}} public Vector3 normalized{get{float m=magnitude; return m>1e-5f? this/m : zero;}} public void Normalize(){this=normalized;}
    public static Vector3 Lerp(Vector3 a,Vector3 b,float t){t=Mathf.Clamp01(t); return a+(b-a)*t;} public static Vector3 Slerp(Vector3 a,Vector3 b,float t){return Lerp(a,b,t).normalized*Mathf.Lerp(a.magnitude,b.magnitude,t);}
    public static float Dot(Vector3 a,Vector3 b){return a.x*b.x+a.y*b.y+a.z*b.z;} public static Vector3 Cross(Vector3 a,Vector3 b){return new Vector3(a.y*b.z-a.z*b.y,a.z*b.x-a.x*b.z,a.x*b.y-a.y*b.x);} public static float Distance(Vector3 a,Vector3 b){return (a-b).magnitude;}
    public static Vector3 ProjectOnPlane(Vector3 v,Vector3 n){n=n.normalized; return v-n*Dot(v,n);} public static Vector3 Scale(Vector3 a,Vector3 b){return new Vector3(a.x*b.x,a.y*b.y,a.z*b.z);} public static Vector3 ClampMagnitude(Vector3 v,float m){return v.magnitude>m? v.normalized*m : v;} public static Vector3 MoveTowards(Vector3 c,Vector3 t,float d){var v=t-c; float m=v.magnitude; return m<=d||m==0? t : c+v/m*d;} public static float Angle(Vector3 a,Vector3 b){float d=Dot(a.normalized,b.normalized); return (float)(Math.Acos(Math.Max(-1,Math.Min(1,d)))*180/Math.PI);} public override string ToString(){return "("+x+", "+y+", "+z+")";} }
  public struct Vector2Int { public int x,y; public Vector2Int(int x,int y){this.x=x;this.y=y;} public int sqrMagnitude{get{return x*x+y*y;}} public static Vector2Int operator-(Vector2Int a,Vector2Int b){return new Vector2Int(a.x-b.x,a.y-b.y);} public static Vector2Int operator+(Vector2Int a,Vector2Int b){return new Vector2Int(a.x+b.x,a.y+b.y);} public static bool operator==(Vector2Int a,Vector2Int b){return a.x==b.x&&a.y==b.y;} public static bool operator!=(Vector2Int a,Vector2Int b){return !(a==b);} public override bool Equals(object o){return o is Vector2Int && (Vector2Int)o==this;} public override int GetHashCode(){return x*73856093^y*19349663;} public override string ToString(){return "("+x+", "+y+")";} }
  public struct Quaternion { public float x,y,z,w; public Quaternion(float x,float y,float z,float w){this.x=x;this.y=y;this.z=z;this.w=w;} public static Quaternion identity{get{return new Quaternion(0,0,0,1);}}
    public static Quaternion AngleAxis(float deg,Vector3 axis){axis=axis.normalized; float h=deg*Mathf.Deg2Rad/2; float s=(float)Math.Sin(h); return new Quaternion(axis.x*s,axis.y*s,axis.z*s,(float)Math.Cos(h));}
    public static Quaternion Euler(float x,float y,float z){return AngleAxis(y,Vector3.up)*AngleAxis(x,Vector3.right)*AngleAxis(z,Vector3.forward);} public static Quaternion Euler(Vector3 e){return Euler(e.x,e.y,e.z);}
    public static Quaternion operator*(Quaternion a,Quaternion b){return new Quaternion(a.w*b.x+a.x*b.w+a.y*b.z-a.z*b.y, a.w*b.y-a.x*b.z+a.y*b.w+a.z*b.x, a.w*b.z+a.x*b.y-a.y*b.x+a.z*b.w, a.w*b.w-a.x*b.x-a.y*b.y-a.z*b.z);}
    public static Vector3 operator*(Quaternion q,Vector3 v){var u=new Vector3(q.x,q.y,q.z); var t=2f*Vector3.Cross(u,v); return v+q.w*t+Vector3.Cross(u,t);}
    public static Quaternion Inverse(Quaternion q){return new Quaternion(-q.x,-q.y,-q.z,q.w);}
    public static Quaternion FromToRotation(Vector3 a,Vector3 b){a=a.normalized;b=b.normalized; var c=Vector3.Cross(a,b); float d=Vector3.Dot(a,b); var q=new Quaternion(c.x,c.y,c.z,1+d); float m=(float)Math.Sqrt(q.x*q.x+q.y*q.y+q.z*q.z+q.w*q.w); return m<1e-5f? identity : new Quaternion(q.x/m,q.y/m,q.z/m,q.w/m);}
    public static Quaternion LookRotation(Vector3 f){return LookRotation(f,Vector3.up);} public static Quaternion LookRotation(Vector3 f,Vector3 up){
      // Like Unity: z = forward, y = up made perpendicular to it, x = y cross z. Falls back to yaw/pitch if up is parallel.
      var z=f.normalized; var x=Vector3.Cross(up,z); if(x.sqrMagnitude<1e-10f){float yaw=(float)Math.Atan2(f.x,f.z)*Mathf.Rad2Deg; float pitch=-(float)Math.Atan2(f.y,Math.Sqrt(f.x*f.x+f.z*f.z))*Mathf.Rad2Deg; return Euler(pitch,yaw,0);}
      x=x.normalized; var y=Vector3.Cross(z,x);
      float m00=x.x,m01=y.x,m02=z.x,m10=x.y,m11=y.y,m12=z.y,m20=x.z,m21=y.z,m22=z.z; float tr=m00+m11+m22; Quaternion q;
      if(tr>0f){float s=(float)Math.Sqrt(tr+1f)*2f; q=new Quaternion((m21-m12)/s,(m02-m20)/s,(m10-m01)/s,0.25f*s);}
      else if(m00>m11&&m00>m22){float s=(float)Math.Sqrt(1f+m00-m11-m22)*2f; q=new Quaternion(0.25f*s,(m01+m10)/s,(m02+m20)/s,(m21-m12)/s);}
      else if(m11>m22){float s=(float)Math.Sqrt(1f+m11-m00-m22)*2f; q=new Quaternion((m01+m10)/s,0.25f*s,(m12+m21)/s,(m02-m20)/s);}
      else {float s=(float)Math.Sqrt(1f+m22-m00-m11)*2f; q=new Quaternion((m02+m20)/s,(m12+m21)/s,0.25f*s,(m10-m01)/s);}
      return q; }
    public static Quaternion Slerp(Quaternion a,Quaternion b,float t){return Lerp(a,b,t);} public static Quaternion Lerp(Quaternion a,Quaternion b,float t){t=Mathf.Clamp01(t); var q=new Quaternion(a.x+(b.x-a.x)*t,a.y+(b.y-a.y)*t,a.z+(b.z-a.z)*t,a.w+(b.w-a.w)*t); float m=(float)Math.Sqrt(q.x*q.x+q.y*q.y+q.z*q.z+q.w*q.w); return new Quaternion(q.x/m,q.y/m,q.z/m,q.w/m);} public static Quaternion RotateTowards(Quaternion a,Quaternion b,float d){return b;} public static float Angle(Quaternion a,Quaternion b){return 0;} public Vector3 eulerAngles{get{return Vector3.zero;}} }
  public struct Matrix4x4 { public static Matrix4x4 TRS(Vector3 p,Quaternion q,Vector3 s){return new Matrix4x4();} }
  public struct Color { public float r,g,b,a; public Color(float r,float g,float b,float a=1){this.r=r;this.g=g;this.b=b;this.a=a;}
    public static Color white{get{return new Color(1,1,1,1);}} public static Color black{get{return new Color(0,0,0,1);}} public static Color clear{get{return new Color(0,0,0,0);}}
    public static Color operator*(Color c,float f){return new Color(c.r*f,c.g*f,c.b*f,c.a*f);} public static Color operator+(Color a,Color b){return new Color(a.r+b.r,a.g+b.g,a.b+b.b,a.a+b.a);} public static implicit operator Color(Color32 c){return new Color(c.r/255f,c.g/255f,c.b/255f,c.a/255f);} public static Color Lerp(Color a,Color b,float t){t=Mathf.Clamp01(t); return new Color(a.r+(b.r-a.r)*t,a.g+(b.g-a.g)*t,a.b+(b.b-a.b)*t,a.a+(b.a-a.a)*t);} }
  public struct Color32 { public byte r,g,b,a; public Color32(byte r,byte g,byte b,byte a){this.r=r;this.g=g;this.b=b;this.a=a;} }
  public struct Rect { public Rect(float x,float y,float w,float h){this.x=x;this.y=y;width=w;height=h;} public float x,y,width,height; public float xMin{get{return x;}} public float xMax{get{return x+width;}} public float yMin{get{return y;}} public float yMax{get{return y+height;}} public Vector2 center{get{return new Vector2(x+width/2,y+height/2);}} public Vector2 size{get{return new Vector2(width,height);}} public Vector2 min{get{return new Vector2(x,y);}} public bool Contains(Vector2 p){return p.x>=x&&p.x<x+width&&p.y>=y&&p.y<y+height;} }
  public class RectOffset { public RectOffset(int a,int b,int c,int d){} }
  public static class Mathf { public const float PI=(float)Math.PI, Deg2Rad=(float)(Math.PI/180), Rad2Deg=(float)(180/Math.PI), Infinity=float.PositiveInfinity;
    public static float Sqrt(float f){return (float)Math.Sqrt(f);} public static float Max(float a,float b){return Math.Max(a,b);} public static int Max(int a,int b){return Math.Max(a,b);} public static float Min(float a,float b){return Math.Min(a,b);} public static int Min(int a,int b){return Math.Min(a,b);}
    public static float Abs(float f){return Math.Abs(f);} public static float Clamp(float v,float a,float b){return v<a?a:v>b?b:v;} public static int Clamp(int v,int a,int b){return v<a?a:v>b?b:v;} public static float Clamp01(float v){return Clamp(v,0,1);} public static float Lerp(float a,float b,float t){return a+(b-a)*Clamp01(t);}
    public static float InverseLerp(float a,float b,float v){return a!=b? Clamp01((v-a)/(b-a)) : 0;} public static float Atan2(float y,float x){return (float)Math.Atan2(y,x);} public static float Cos(float f){return (float)Math.Cos(f);} public static float Sin(float f){return (float)Math.Sin(f);} public static float Tan(float f){return (float)Math.Tan(f);} public static float Asin(float f){return (float)Math.Asin(f);} public static float Acos(float f){return (float)Math.Acos(f);} public static float Exp(float f){return (float)Math.Exp(f);}
    public static float Repeat(float t,float l){return t-(float)Math.Floor(t/l)*l;} public static float PingPong(float t,float l){t=Repeat(t,l*2); return l-Math.Abs(t-l);} public static int RoundToInt(float f){return (int)Math.Round(f, MidpointRounding.ToEven);} public static int CeilToInt(float f){return (int)Math.Ceiling(f);} public static int FloorToInt(float f){return (int)Math.Floor(f);} public static float Floor(float f){return (float)Math.Floor(f);} public static float Round(float f){return (float)Math.Round(f);} public static float Ceil(float f){return (float)Math.Ceiling(f);} public static bool Approximately(float a,float b){return Math.Abs(a-b)<1e-6f;} public static float Sign(float f){return f>=0?1:-1;} public static float Pow(float a,float b){return (float)Math.Pow(a,b);} public static float SmoothStep(float a,float b,float t){t=Clamp01(t); t=t*t*(3-2*t); return a+(b-a)*t;} public static float MoveTowards(float c,float t,float d){return Math.Abs(t-c)<=d? t : c+Math.Sign(t-c)*d;} public static float DeltaAngle(float a,float b){float d=Repeat(b-a,360); if(d>180)d-=360; return d;} public static float MoveTowardsAngle(float c,float t,float d){float delta=DeltaAngle(c,t); return Math.Abs(delta)<=d? t : c+Math.Sign(delta)*d;} }
  public static class Random { static System.Random r=new System.Random(1); public static float value{get{return (float)r.NextDouble();}} public static Vector3 insideUnitSphere{get{Vector3 v; do { v=new Vector3(value*2f-1f,value*2f-1f,value*2f-1f);} while(v.sqrMagnitude>1f); return v;}} public static float Range(float a,float b){return a+(b-a)*value;} public static int Range(int a,int b){return b>a? r.Next(a,b) : a;} public static Vector2 insideUnitCircle{get{float t=value*6.283f, d=(float)Math.Sqrt(value); return new Vector2((float)Math.Cos(t)*d,(float)Math.Sin(t)*d);}} public static void InitState(int s){r=new System.Random(s);} }
  public static class Time { public static int frameCount; public static float fixedDeltaTime, time, deltaTime, unscaledDeltaTime, unscaledTime, timeScale; }
  public static class Screen { public static int width, height; }
  public static class Debug { public static void Log(object o){} }
  public static class PlayerPrefs { static Dictionary<string,object> d=new Dictionary<string,object>(); public static string GetString(string k,string def){object v; return d.TryGetValue(k,out v)?(string)v:def;} public static void SetString(string k,string v){d[k]=v;} public static int GetInt(string k,int def){object v; return d.TryGetValue(k,out v)?(int)v:def;} public static void SetInt(string k,int v){d[k]=v;} public static float GetFloat(string k,float def){object v; return d.TryGetValue(k,out v)?(float)v:def;} public static void SetFloat(string k,float v){d[k]=v;} public static void Save(){} public static void DeleteAll(){d.Clear();} public static bool HasKey(string k){return d.ContainsKey(k);} public static void DeleteKey(string k){d.Remove(k);} }
  public static class JsonUtility { public static T FromJson<T>(string s){return default(T);} public static string ToJson(object o){return "";} }
  public enum TextureFormat { RGBA32 } public enum FilterMode { Point, Bilinear } public enum TextureWrapMode { Clamp, Repeat }
  public class Texture : Object {} 
  public class Texture2D : Texture { public Color[] pixels; public Texture2D(int w,int h){width=w;height=h;pixels=new Color[w*h];} public Texture2D(int w,int h,TextureFormat f,bool m):this(w,h){} public int width,height; public FilterMode filterMode; public TextureWrapMode wrapMode; public void SetPixel(int x,int y,Color c){if(x>=0&&y>=0&&x<width&&y<height)pixels[y*width+x]=c;} public Color GetPixel(int x,int y){return pixels[y*width+x];} public void Apply(){} public static Texture2D whiteTexture; }
  public enum SpriteMeshType { FullRect, Tight }
  public class Sprite : Object { public Texture2D texture; public Vector2 pivot; public static Sprite Create(Texture2D t,Rect r,Vector2 p,float ppu,uint extrude,SpriteMeshType m){return new Sprite{texture=t,pivot=new Vector2(p.x*r.width,p.y*r.height)};} }
  public enum SpriteDrawMode { Simple, Sliced, Tiled }
  public class Renderer : Component { public bool enabled; public int sortingOrder; public Material sharedMaterial, material; public Material[] sharedMaterials; public UnityEngine.Rendering.ShadowCastingMode shadowCastingMode; }
  public class MeshRenderer : Renderer {}
  public class SpriteRenderer : Renderer { public Sprite sprite; public Color color; public SpriteDrawMode drawMode; public Vector2 size; }
  public class AudioClip : Object { public float[] data; public int frequency; public static AudioClip Create(string n,int len,int ch,int freq,bool stream){return new AudioClip{name=n,data=new float[len],frequency=freq};} public bool SetData(float[] d,int offset){Array.Copy(d,0,data,offset,d.Length); return true;} }
  public class AudioSource : Behaviour { public bool playOnAwake, loop, isPlaying; public float spatialBlend, volume, pitch, panStereo, minDistance, maxDistance, dopplerLevel; public AudioRolloffMode rolloffMode; public AudioClip clip; public void Play(){isPlaying=true;} public void Stop(){isPlaying=false;} public void PlayOneShot(AudioClip c, float v=1f){} }
  public enum AudioRolloffMode { Logarithmic, Linear, Custom }
  public class AudioListener : Behaviour { public static float volume = 1f; }
  public enum CameraClearFlags { SolidColor }
  public class Camera : Behaviour { public static Camera main; public bool orthographic; public float orthographicSize, fieldOfView, nearClipPlane, farClipPlane; public CameraClearFlags clearFlags; public Color backgroundColor; public Vector3 ScreenToWorldPoint(Vector3 v){return v;} public Vector3 WorldToScreenPoint(Vector3 v){return v;} }
  public enum RigidbodyInterpolation2D { None, Interpolate } public enum CollisionDetectionMode2D { Discrete, Continuous }
  public class Rigidbody2D : Component { public float gravityScale; public bool freezeRotation; public RigidbodyInterpolation2D interpolation; public CollisionDetectionMode2D collisionDetectionMode;
#if UNITY_6000_0_OR_NEWER
    public Vector2 linearVelocity;
#else
    public Vector2 velocity;
#endif
  }
  public class Collider2D : Behaviour { public bool isTrigger; } public class CircleCollider2D : Collider2D { public float radius; } public class BoxCollider2D : Collider2D { public Vector2 size; }
  public struct RaycastHit2D { public Collider2D collider; public float fraction; public Vector2 point; }
  public struct ContactFilter2D { public ContactFilter2D NoFilter(){return this;} }
  public static class Physics2D { public static Vector2 gravity; public static int Linecast(Vector2 a,Vector2 b,ContactFilter2D f,List<RaycastHit2D> r){return 0;} public static int CircleCast(Vector2 o,float r,Vector2 d,ContactFilter2D f,List<RaycastHit2D> res,float dist){return 0;} }
  public enum KeyCode { None, Space, F, Tab, W,A,S,D,UpArrow,DownArrow,LeftArrow,RightArrow,LeftShift,C,LeftControl,R,H,B,Q,E,Escape,Alpha1,Alpha2,Alpha3 }
  public static class Input { public static float GetAxisRaw(string a){return 0;} public static float GetAxis(string a){return 0;} public static Vector2 mouseScrollDelta; public static bool GetKey(KeyCode k){return false;} public static bool GetKeyDown(KeyCode k){return false;} public static bool GetMouseButton(int b){return false;} public static bool GetMouseButtonDown(int b){return false;} public static Vector3 mousePosition; }
  public enum RuntimeInitializeLoadType { AfterSceneLoad, SubsystemRegistration }
  public class RuntimeInitializeOnLoadMethodAttribute : Attribute { public RuntimeInitializeOnLoadMethodAttribute(RuntimeInitializeLoadType t){} }
  public class CreateAssetMenuAttribute : Attribute { public string menuName, fileName; }
  public class HeaderAttribute : Attribute { public HeaderAttribute(string s){} }
  public class TooltipAttribute : Attribute { public TooltipAttribute(string s){} }
  public class RequireComponent : Attribute { public RequireComponent(Type t){} public RequireComponent(Type a, Type b){} public RequireComponent(Type a, Type b, Type c){} }
  public enum TextAnchor { UpperLeft, UpperCenter, UpperRight, MiddleLeft, MiddleCenter, MiddleRight, LowerLeft, LowerCenter, LowerRight } public enum FontStyle { Normal, Bold } public enum ScaleMode { StretchToFill }
  public class GUIStyleState { public Color textColor; public Texture2D background; }
  public class GUIStyle { public GUIStyle(GUIStyle o){} public int fontSize; public bool richText, wordWrap; public TextAnchor alignment; public FontStyle fontStyle; public GUIStyleState normal; public RectOffset padding; }
  public class GUIContent { public static GUIContent none; }
  public class GUISkin { public GUIStyle label, box, button, toggle; }
  public class GUILayoutOption {}
  public enum EventType { Layout, Repaint, MouseDown, MouseUp }
  public class Event { public static Event current = new Event(); public EventType type; }
  public static class Cursor { public static bool visible; public static CursorLockMode lockState; }
  public static class GUIUtility { public static void RotateAroundPivot(float a, Vector2 p){} }
  public static class GUILayoutUtility { public static Rect GetRect(float w,float h,params GUILayoutOption[] o){return new Rect(0,0,w,h);} }
  public static class GUI { public static GUISkin skin; public static Matrix4x4 matrix; public static Color color, backgroundColor; public static bool enabled;
    public static void Label(Rect r,string t,GUIStyle s){} public static bool Button(Rect r,string t){return false;} public static void DrawTexture(Rect r,Texture t){} public static void BeginGroup(Rect r){} public static void EndGroup(){} public static void Box(Rect r,GUIContent c,GUIStyle s){} public static void Box(Rect r,GUIContent c){} public static void DrawTexture(Rect r,Texture t,ScaleMode m,bool a,float asp,Color c,float bw,float br){} }
  public static class GUILayout { public static void BeginArea(Rect r,GUIStyle s){} public static void BeginArea(Rect r){} public static void EndArea(){} public static void Label(string t,GUIStyle s,params GUILayoutOption[] o){} public static bool Button(string t,params GUILayoutOption[] o){return false;}
    public static bool Toggle(bool v,string t,params GUILayoutOption[] o){return v;} public static bool Toggle(bool v,string t,GUIStyle s,params GUILayoutOption[] o){return v;} public static void Space(float f){} public static Vector2 BeginScrollView(Vector2 p,params GUILayoutOption[] o){return p;} public static void EndScrollView(){} public static float HorizontalSlider(float v,float a,float b,params GUILayoutOption[] o){return v;} public static void BeginVertical(GUIStyle s,params GUILayoutOption[] o){} public static void FlexibleSpace(){} public static void BeginHorizontal(params GUILayoutOption[] o){} public static void EndHorizontal(){} public static void BeginVertical(params GUILayoutOption[] o){} public static void EndVertical(){}
    public static GUILayoutOption Height(float h){return null;} public static GUILayoutOption Width(float w){return null;} }
}
namespace UnityEngine.Rendering { public enum IndexFormat { UInt16, UInt32 } public enum AmbientMode { Skybox, Trilight, Flat, Custom } public enum ShadowCastingMode { Off, On, TwoSided, ShadowsOnly } }
namespace UnityEngine.InputSystem.Controls { public class ButtonControl { public bool isPressed, wasPressedThisFrame; } public class KeyControl : ButtonControl {} public class Vector2Control { public UnityEngine.Vector2 ReadValue(){return new UnityEngine.Vector2();} } }
namespace UnityEngine.InputSystem { using Controls;
  public class Keyboard { public static Keyboard current; public KeyControl wKey,aKey,sKey,dKey,upArrowKey,downArrowKey,leftArrowKey,rightArrowKey,leftShiftKey,cKey,leftCtrlKey,rKey,hKey,bKey,fKey,spaceKey,tabKey,qKey,eKey,escapeKey,digit1Key,digit2Key,digit3Key; }
  public class Mouse { public static Mouse current; public ButtonControl leftButton, rightButton, middleButton; public Vector2Control position, delta, scroll; } }
namespace UnityEngine {
  public struct Vector4 {
    public float x, y, z, w;
    public Vector4(float x, float y, float z, float w) { this.x = x; this.y = y; this.z = z; this.w = w; }
    public static Vector4 zero { get { return new Vector4(0f, 0f, 0f, 0f); } }
    public override string ToString() { return "(" + x + ", " + y + ", " + z + ", " + w + ")"; }
  }
}

namespace UnityEngine { public static class Application { public static bool isEditor; public static void Quit(){} } }
namespace UnityEngine { public class TextAsset : Object { public byte[] bytes = new byte[0]; public string text = ""; } public static class Resources { public static T Load<T>(string path) where T : Object { return null; } } }
